'use server';
/**
 * @fileOverview An AI agent that acts as a language tutor chatbot.
 *
 * - getChatbotResponse - A function that handles the chatbot conversation.
 * - ChatbotInput - The input type for the getChatbotResponse function.
 * - ChatbotOutput - The return type for the getChatbotResponse function.
 */

import {ai} from '@/ai/genkit';
import {Message} from 'genkit';
import {z} from 'genkit';

const ChatbotInputSchema = z.object({
  userInput: z.string(),
  targetLanguage: z.string().describe('The language the user wants to practice.'),
  history: z
    .array(
      z.object({
        role: z.enum(['user', 'model']),
        parts: z.array(z.object({text: z.string()})),
      })
    )
    .optional()
    .describe('The previous conversation history.'),
});
export type ChatbotInput = z.infer<typeof ChatbotInputSchema>;

const ChatbotOutputSchema = z.object({
  response: z.string().describe("The chatbot tutor's response in the target language."),
});
export type ChatbotOutput = z.infer<typeof ChatbotOutputSchema>;

export async function getChatbotResponse(input: ChatbotInput): Promise<ChatbotOutput> {
  return chatbotFlow(input);
}

const chatbotFlow = ai.defineFlow(
  {
    name: 'chatbotFlow',
    inputSchema: ChatbotInputSchema,
    outputSchema: ChatbotOutputSchema,
  },
  async ({userInput, targetLanguage, history}) => {
    const systemPrompt = `You are a friendly and encouraging language tutor. Your name is Kai.
Your goal is to help the user practice speaking in ${targetLanguage}.
ALWAYS respond in ${targetLanguage}, no matter what the user says.
Keep your responses conversational, concise, and natural.
If the user makes a small mistake, gently correct them by providing the correct phrasing. For example, if they say "I is happy" in English, you could respond with "That's close! A more natural way to say that is 'I am happy'. What makes you happy today?". Adapt this correction style to ${targetLanguage}.
If this is the first message from the user (history is empty), introduce yourself and ask them what they'd like to talk about in ${targetLanguage}.`;

    const messages: Message[] = history || [];
    messages.push({role: 'user', parts: [{text: userInput}]});

    const result = await ai.generate({
      model: 'googleai/gemini-2.0-flash',
      system: systemPrompt,
      messages: messages,
      output: {
        format: 'json',
        schema: ChatbotOutputSchema,
      },
    });
    
    const output = result.output;
    if (!output) {
        throw new Error("No output generated by the model.");
    }
    
    return output;
  }
);
