'use server';

/**
 * @fileOverview An AI agent that acts as a language tutor chatbot.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// Input validation schema
const ChatbotInputSchema = z.object({
  userInput: z.string(),
  targetLanguage: z.string().describe('The language the user wants to practice.'),
  history: z
    .array(
      z.object({
        role: z.enum(['user', 'model']),
        parts: z.array(z.object({ text: z.string() })),
      })
    )
    .optional()
    .describe('The previous conversation history.'),
});
export type ChatbotInput = z.infer<typeof ChatbotInputSchema>;

// Output validation schema
const ChatbotOutputSchema = z.object({
  response: z.string().describe("The chatbot tutor's response in the target language."),
});
export type ChatbotOutput = z.infer<typeof ChatbotOutputSchema>;

// Main exported function
export async function getChatbotResponse(input: ChatbotInput): Promise<ChatbotOutput> {
  try {
    const result = await chatbotFlow(input);
    return result;
  } catch (error: any) {
    console.error('[Chatbot Flow Error]', error);

    return {
      response:
        "Sorry 😔, I couldn't process your request right now. Please try again shortly or check your network.",
    };
  }
}


const chatbotFlow = ai.defineFlow(
  {
    name: 'chatbotFlow',
    inputSchema: ChatbotInputSchema,
    outputSchema: ChatbotOutputSchema,
    // If your GenKit version lets you set a default model for the flow, do it here:
    // model: 'googleai/gemini-2.0-flash',
  },
  async ({ userInput, targetLanguage, history }) => {
    const isFirstMessage = !history || history.length === 0;

    // 1) build the system prompt
    const systemPrompt = `
You are a friendly and encouraging language tutor. Your name is Kai.
Your goal is to help the user practice speaking in ${targetLanguage}.
ALWAYS respond in ${targetLanguage}, no matter what the user says.
Keep your responses conversational, concise, and natural.
If the user makes a small mistake, gently correct them by providing the correct phrasing.
For example, if they say "I is happy" in English, you could respond with:
"That's close! A more natural way to say that is 'I am happy'. What makes you happy today?".
Adapt this correction style to ${targetLanguage}.

${isFirstMessage
  ? `This is the first message. Introduce yourself and ask what the user wants to talk about in ${targetLanguage}.`
  : ''}
`.trim();

    // 2) assemble all parts into a flat array
    type Part = { text: string; role: 'system' | 'user' | 'model' };

    const parts: Part[] = [];

    // system message
    parts.push({ text: systemPrompt, role: 'system' });

    // history
    if (history) {
      for (const msg of history) {
        for (const p of msg.parts) {
          parts.push({ text: p.text, role: msg.role });
        }
      }
    }

    // current user input
    parts.push({ text: userInput, role: 'user' });

    // 3) call ai.generate with the parts array
    const result = await ai.generate(parts);

      // 4) extract and return
      const responseText = result.text?.trim();
      if (!responseText) {
        throw new Error("No output generated by the model.");
      }


    return { response: responseText };
  }
);
