// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A translation AI agent that translates with slang and colloquialisms.
 *
 * - translateWithSlang - A function that handles the translation process.
 * - TranslateWithSlangInput - The input type for the translateWithSlang function.
 * - TranslateWithSlangOutput - The return type for the translateWithSlang function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const TranslateWithSlangInputSchema = z.object({
  text: z.string().describe('The text to translate.'),
  sourceLanguage: z.string().describe('The language of the text to translate.'),
  targetLanguage: z.string().describe('The language to translate the text into.'),
});
export type TranslateWithSlangInput = z.infer<typeof TranslateWithSlangInputSchema>;

const TranslateWithSlangOutputSchema = z.object({
  translation: z.string().describe('The translated text, with slang terms accounted for.'),
});
export type TranslateWithSlangOutput = z.infer<typeof TranslateWithSlangOutputSchema>;

export async function translateWithSlang(input: TranslateWithSlangInput): Promise<TranslateWithSlangOutput> {
  return translateWithSlangFlow(input);
}

const prompt = ai.definePrompt({
  name: 'translateWithSlangPrompt',
  input: {schema: TranslateWithSlangInputSchema},
  output: {schema: TranslateWithSlangOutputSchema},
  prompt: `You are a multilingual translator who specializes in understanding and translating slang terms and colloquialisms.

  Translate the following text from {{sourceLanguage}} to {{targetLanguage}}, ensuring that any slang terms or colloquialisms are accurately translated with culturally relevant equivalents in the target language. The goal is to make the translation sound natural and understandable to a native speaker of the target language.

  Text: {{{text}}}`,
});

const translateWithSlangFlow = ai.defineFlow(
  {
    name: 'translateWithSlangFlow',
    inputSchema: TranslateWithSlangInputSchema,
    outputSchema: TranslateWithSlangOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
