export const languages = [
  { name: 'Afrikaans', code: 'af-ZA' },
  { name: 'Albanian', code: 'sq-AL' },
  { name: 'Amharic', code: 'am-ET' },
  { name: 'Arabic', code: 'ar-SA' },
  { name: 'Armenian', code: 'hy-AM' },
  { name: 'Azerbaijani', code: 'az-AZ' },
  { name: 'Basque', code: 'eu-ES' },
  { name: 'Belarusian', code: 'be-BY' },
  { name: 'Bengali', code: 'bn-BD' },
  { name: 'Bosnian', code: 'bs-BA' },
  { name: 'Bulgarian', code: 'bg-BG' },
  { name: 'Catalan', code: 'ca-ES' },
  { name: 'Cebuano', code: 'ceb-PH' },
  { name: 'Chinese (Simplified)', code: 'zh-CN' },
  { name: 'Chinese (Traditional)', code: 'zh-TW' },
  { name: 'Corsican', code: 'co-FR' },
  { name: 'Croatian', code: 'hr-HR' },
  { name: 'Czech', code: 'cs-CZ' },
  { name: 'Danish', code: 'da-DK' },
  { name: 'Dutch', code: 'nl-NL' },
  { name: 'English', code: 'en-US' },
  { name: 'Esperanto', code: 'eo-UY' },
  { name: 'Estonian', code: 'et-EE' },
  { name: 'Finnish', code: 'fi-FI' },
  { name: 'French', code: 'fr-FR' },
  { name: 'Frisian', code: 'fy-NL' },
  { name: 'Galician', code: 'gl-ES' },
  { name: 'Georgian', code: 'ka-GE' },
  { name: 'German', code: 'de-DE' },
  { name: 'Greek', code: 'el-GR' },
  { name: 'Gujarati', code: 'gu-IN' },
  { name: 'Haitian Creole', code: 'ht-HT' },
  { name: 'Hausa', code: 'ha-NG' },
  { name: 'Hawaiian', code: 'haw-US' },
  { name: 'Hebrew', code: 'he-IL' },
  { name: 'Hindi', code: 'hi-IN' },
  { name: 'Hmong', code: 'hmn-CN' },
  { name: 'Hungarian', code: 'hu-HU' },
  { name: 'Icelandic', code: 'is-IS' },
  { name: 'Igbo', code: 'ig-NG' },
  { name: 'Indonesian', code: 'id-ID' },
  { name: 'Irish', code: 'ga-IE' },
  { name: 'Italian', code: 'it-IT' },
  { name: 'Japanese', code: 'ja-JP' },
  { name: 'Javanese', code: 'jv-ID' },
  { name: 'Kannada', code: 'kn-IN' },
  { name: 'Kazakh', code: 'kk-KZ' },
  { name: 'Khmer', code: 'km-KH' },
  { name: 'Kinyarwanda', code: 'rw-RW' },
  { name: 'Korean', code: 'ko-KR' },
  { name: 'Kurdish', code: 'ku-TR' },
  { name: 'Kyrgyz', code: 'ky-KG' },
  { name: 'Lao', code: 'lo-LA' },
  { name: 'Latin', code: 'la-VA' },
  { name: 'Latvian', code: 'lv-LV' },
  { name: 'Lithuanian', code: 'lt-LT' },
  { name: 'Luxembourgish', code: 'lb-LU' },
  { name: 'Macedonian', code: 'mk-MK' },
  { name: 'Malagasy', code: 'mg-MG' },
  { name: 'Malay', code: 'ms-MY' },
  { name: 'Malayalam', code: 'ml-IN' },
  { name: 'Maltese', code: 'mt-MT' },
  { name: 'Maori', code: 'mi-NZ' },
  { name: 'Marathi', code: 'mr-IN' },
  { name: 'Mongolian', code: 'mn-MN' },
  { name: 'Myanmar (Burmese)', code: 'my-MM' },
  { name: 'Nepali', code: 'ne-NP' },
  { name: 'Norwegian', code: 'no-NO' },
  { name: 'Nyanja (Chichewa)', code: 'ny-MW' },
  { name: 'Odia (Oriya)', code: 'or-IN' },
  { name: 'Pashto', code: 'ps-AF' },
  { name: 'Persian', code: 'fa-IR' },
  { name: 'Polish', code: 'pl-PL' },
  { name: 'Portuguese', code: 'pt-PT' },
  { name: 'Punjabi', code: 'pa-IN' },
  { name: 'Romanian', code: 'ro-RO' },
  { name: 'Russian', code: 'ru-RU' },
  { name: 'Samoan', code: 'sm-WS' },
  { name: 'Scots Gaelic', code: 'gd-GB' },
  { name: 'Serbian', code: 'sr-RS' },
  { name: 'Sesotho', code: 'st-LS' },
  { name: 'Shona', code: 'sn-ZW' },
  { name: 'Sindhi', code: 'sd-PK' },
  { name: 'Sinhala (Sinhalese)', code: 'si-LK' },
  { name: 'Slovak', code: 'sk-SK' },
  { name: 'Slovenian', code: 'sl-SI' },
  { name: 'Somali', code: 'so-SO' },
  { name: 'Spanish', code: 'es-ES' },
  { name: 'Sundanese', code: 'su-ID' },
  { name: 'Swahili', code: 'sw-KE' },
  { name: 'Swedish', code: 'sv-SE' },
  { name: 'Tagalog (Filipino)', code: 'tl-PH' },
  { name: 'Tajik', code: 'tg-TJ' },
  { name: 'Tamil', code: 'ta-IN' },
  { name: 'Tatar', code: 'tt-RU' },
  { name: 'Telugu', code: 'te-IN' },
  { name: 'Thai', code: 'th-TH' },
  { name: 'Turkish', code: 'tr-TR' },
  { name: 'Turkmen', code: 'tk-TM' },
  { name: 'Ukrainian', code: 'uk-UA' },
  { name: 'Urdu', code: 'ur-PK' },
  { name: 'Uyghur', code: 'ug-CN' },
  { name: 'Uzbek', code: 'uz-UZ' },
  { name: 'Vietnamese', code: 'vi-VN' },
  { name: 'Welsh', code: 'cy-GB' },
  { name: 'Xhosa', code: 'xh-ZA' },
  { name: 'Yiddish', code: 'yi-DE' },
  { name: 'Yoruba', code: 'yo-NG' },
  { name: 'Zulu', code: 'zu-ZA' },
];
